# Zabbix Agent 2 PostgreSQL plugin custom query configuration
# Copy this file or the lines below into /etc/zabbix/zabbix_agent2.d/postgresql_custom.conf

Plugins.PostgreSQL.CustomQueriesEnabled=true
Plugins.PostgreSQL.CustomQueriesPath=/etc/zabbix/zabbix_agent2.d/custom_scripts
Plugins.PostgreSQL.Default.Database=postgres
